spring:
  application:
    name: teste-mirante-cidades
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/db_teste_mirante?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: postgres
  flyway:
    postgresql:
      transactional-lock: false


